[build]
  command   = "npm run build"
  publish   = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express", "serverless-http"]

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/generate/:splat"
  status = 200
  force = true